# Generated by Django 5.0.1 on 2024-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('key_name', models.CharField(blank=True, max_length=50, null=True)),
                ('key_text', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['session', 'key_name'],
            },
        ),
    ]
