"""
Django settings for sentryx project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATAFOLDER = BASE_DIR
if config('DATAFOLDER', default=None) is not None:
    DATAFOLDER = config('DATAFOLDER')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$%=^78v8ydshkb7pd_8vieh(7_dmq0niow3zy85$6y_hto1zn$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_allowed_hosts = config('ALLOWEDHOSTS', default=None)
if _allowed_hosts is not None:
    ALLOWED_HOSTS = _allowed_hosts.split(',')
else:
    ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    "export.apps.ExportConfig",
    "home.apps.HomeConfig",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'home.sessionmw.SessionMiddleware',
]

ROOT_URLCONF = 'sentryx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sentryx.contextprocessor.add_company_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'sentryx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATAFOLDER + 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# cors headers
originlist = config('CORS_ALLOWED_ORIGINS', default=None)
if originlist is not None:
    CORS_ALLOWED_ORIGINS = originlist.split(',')
else:
    CORS_ALLOW_ALL_ORIGINS = True
originlist = []

# cors whitelist
whitelist = config('CORS_ORIGIN_WHITELIST', default=None)
if whitelist is not None:
    CORS_ORIGIN_WHITELIST = whitelist.split(',')
else:
    CORS_ORIGIN_WHITELIST = []
whitelist = []

# cors trusted origins
trusted = config('CSRF_TRUSTED_ORIGINS', default=None)
if trusted is not None:
    CSRF_TRUSTED_ORIGINS = trusted.split(',')
else:
    CSRF_TRUSTED_ORIGINS = []

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
#    BASE_DIR / '/static/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = ''
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
HOME_URL = '/'
LOGOUT_REDIRECT_URL = '/'
